// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_sharing_is_caring = ""; // <GPGSID>
        public const string achievement_shopaholic = ""; // <GPGSID>
        public const string achievement_take_the_easy_way_out = ""; // <GPGSID>
        public const string achievement_look_at_me_ma_im_flying = ""; // <GPGSID>
        public const string achievement_cool_down = ""; // <GPGSID>
        public const string achievement_level_3_pro = ""; // <GPGSID>
        public const string achievement_level_6_pro = ""; // <GPGSID>
        public const string achievement_dedicated = ""; // <GPGSID>
        public const string achievement_social_media_addict = ""; // <GPGSID>
        public const string leaderboard_best_time__level_2 = ""; // <GPGSID>
        public const string leaderboard_best_time__level_3 = ""; // <GPGSID>
        public const string achievement_weeeee = ""; // <GPGSID>
        public const string achievement_level_2_pro = ""; // <GPGSID>
        public const string achievement_critic = ""; // <GPGSID>
        public const string achievement_sodium_overload = ""; // <GPGSID>
        public const string achievement_third_degree_burn = ""; // <GPGSID>
        public const string achievement_mmmm_popcorn = ""; // <GPGSID>
        public const string achievement_level_5_pro = ""; // <GPGSID>
        public const string achievement_level_8_pro = ""; // <GPGSID>
        public const string achievement_ready_for_more = ""; // <GPGSID>
        public const string achievement_level_9_pro = ""; // <GPGSID>
        public const string achievement_law_of_attraction = ""; // <GPGSID>
        public const string leaderboard_best_time__level_1 = ""; // <GPGSID>
        public const string achievement_popcorn_addict = ""; // <GPGSID>
        public const string achievement_level_10_pro = ""; // <GPGSID>
        public const string achievement_cant_take_the_heat = ""; // <GPGSID>
        public const string leaderboard_best_time__level_5 = ""; // <GPGSID>
        public const string leaderboard_best_time__level_6 = ""; // <GPGSID>
        public const string leaderboard_best_time__level_7 = ""; // <GPGSID>
        public const string leaderboard_best_time__level_8 = ""; // <GPGSID>
        public const string leaderboard_best_time__level_9 = ""; // <GPGSID>
        public const string achievement_apply_water_to_burned_area = ""; // <GPGSID>
        public const string achievement_make_a_wish = ""; // <GPGSID>
        public const string achievement_level_1_pro = ""; // <GPGSID>
        public const string achievement_level_4_pro = ""; // <GPGSID>
        public const string achievement_level_7_pro = ""; // <GPGSID>
        public const string leaderboard_best_time__level_10 = ""; // <GPGSID>
        public const string achievement_it_burns = ""; // <GPGSID>
        public const string achievement_never_give_up = ""; // <GPGSID>
        public const string leaderboard_best_time__level_4 = ""; // <GPGSID>

}

